<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: values taken in
### Hidden Layer: any layer in between the input and output
### Output Layer: value computed per given input
### Neuron: any individual hidden or output cell or node in a neural network
### Weight: a number multplied to an input
### Activation Function: a transfer function that decides how much signal to transfer to the next level
### Node Map: diagram of the node connectivity
### Perceptron: a neural network with a single node (output cell)


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Start with the inputs. To calculate each node in the next layer, the inputs are multiplied by a weight. Those weights are summed, and a bias variable is also added. Next an activation function is applied. The result is the output. 


## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [ ]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [ ]:
list(df)

In [ ]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [ ]:
# inputs
inputs = np.array(df[["x1","x2"]])
# add bias variable
inputs = np.append(inputs, [[1],[1],[1],[1]],axis = 1)
# Correct outputs
correct_outputs = np.array(df[["y"]])

In [ ]:
inputs

In [ ]:
correct_outputs

In [ ]:
# selecting random weights tot start
weights = (2 * np.random.random((3,1)) - 1)
weights

In [ ]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

In [ ]:
# predicted outputs
activated_outputs = sigmoid(weighted_sum)
activated_outputs

In [ ]:
correct_outputs

In [ ]:
# measuring error
error = correct_outputs - activated_outputs
error

In [ ]:
# adjusting weight
adjustments = error * sigmoid_derivative(weighted_sum)
adjustments

In [ ]:
# new weights
weights += np.dot(inputs.T, adjustments)
weights

In [ ]:
# Updated weights over 1000 iterations
for iteration in range(1000):
    weighted_sum = np.dot(inputs, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)    

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [305]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [328]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

target = ['Outcome']
feats = list(diabetes)[:-1]
X = diabetes[feats]
y = np.array(diabetes[target])

scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [327]:
X.shape

(768, 8)

In [ ]:
y.shape

In [339]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1+ np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)   

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # Add bias var
        bias = []
        for i in range(len(X)):
            bias += [[1]]
        X = np.append(X, bias,axis = 1)
        
        # Randomly Initialize Weights
        self.weights = (2 * np.random.random((X.shape[1], 1)) - 1)
        
        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)
            # Activate!
            activated_output = sigmoid_derivative(weighted_sum)
            # Cac error
            error = y - activated_output
            # Update the Weights
            adjustments = error * sigmoid_derivative(weighted_sum)
            self.weights += np.dot(X.T, adjustments)
        return self 

    def activate(self, X):
        """Calculate net input"""
        # Add bias var
        bias = []
        for i in range(len(X)):
            bias += [[1]]
        X = np.append(X, bias,axis = 1)
        
        weighted_sum = np.dot(X, self.weights)
        activated_output = sigmoid(weighted_sum)
        return activated_output
    
    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.activate(X) >= .5, 1, 0)

In [340]:
pn = Perceptron()

In [341]:
pn.fit(X, y)

In [343]:
pn.weights
pn.activate(X)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [344]:
pn.predict(X)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?